name: Publish to AUR

on:
  push:
    tags:
      - "v*"

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Fix the "dubious ownership" Git error (critical!)
      - name: Fix Git safe directory
        run: git config --global --add safe.directory '*'

      # Deploy to AUR using the official action
      - name: Publish to AUR
        uses: anas-elgarhy/aur-release-action@v3.8
        with:
          package_name: phantimer
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_username: "aman-sanin"
          git_email: "amansaninkmct@gmail.com"
          commit_message: "Update to version %VERSION%"
