name: Publish to AUR

on:
  push:
    tags:
      - 'v*'  # Triggers when you push a tag like v0.1.0

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: git config --global --add safe.directory /github/workspace

      - name: Publish AUR package
        uses: anas-elgarhy/aur-release-action@v3.8
        with:
          package_name: phantimer                              
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}  
          github_token: ${{ secrets.GITHUB_TOKEN }}            
          git_username: "aman-sanin"                           
          git_email: "amansaninkmct@gmail.com"
